spring:
  application:
    name: my-store-api
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration : 900 #5m
    refreshTokenExpiration : 604800 #7d
