spring:
  application:
    name: my-store-api
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration : 900 #15m
    refreshTokenExpiration : 604800 #7d
  profiles:
    active: dev
stripe:
  secretkey: ${STRIPE_SECRET_KEY}
  webhookSecretkey: ${STRIPE_WEBHOOK_SECRET_KEY}
